project:
  type: website

website:
  title: "PYT002"
  navbar:
    left:
      - href: index.qmd
        text: Acerca de...
      - about.qmd
  repo-url: https://github.com/Laboratoria/UPSK-PYT002-Site
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



